# Generated by Django 5.0.2 on 2026-03-03 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Número de orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('shipping_address', models.TextField(verbose_name='Dirección de envío')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('shipping_state', models.CharField(max_length=100, verbose_name='Estado')),
                ('shipping_postal_code', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('shipping_phone', models.CharField(max_length=15, verbose_name='Teléfono de contacto')),
                ('payment_method', models.CharField(choices=[('card', 'Tarjeta de crédito/débito'), ('transfer', 'Transferencia bancaria'), ('cash', 'Efectivo')], default='card', max_length=20, verbose_name='Método de pago')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado del pago')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de pago')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Historial de orden',
                'verbose_name_plural': 'Historial de órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de orden',
                'verbose_name_plural': 'Items de orden',
            },
        ),
    ]
