# Generated by Django 5.0.2 on 2026-03-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Recoger en punto físico'), ('home_delivery', 'Envío a domicilio')], default='home_delivery', max_length=20, verbose_name='Método de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_slot',
            field=models.CharField(blank=True, default='9:00 AM - 6:00 PM', max_length=50, verbose_name='Horario de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.CharField(blank=True, choices=[('mercado', '📍 Punto 1 – Mercado'), ('segundo_lugar', '📍 Punto 2 – Segundo lugar físico')], max_length=20, null=True, verbose_name='Punto de recogida'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='Dirección de envío'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('ready_for_pickup', 'Listo para recoger'), ('picked_up', 'Recogido')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('ready_for_pickup', 'Listo para recoger'), ('picked_up', 'Recogido')], max_length=20, verbose_name='Estado'),
        ),
    ]
