# Generated by Django 5.0.2 on 2026-03-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_method_order_delivery_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal')], default='card', max_length=20, verbose_name='Método de pago'),
        ),
    ]
