# Generated by Django 5.0.2 on 2026-03-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de orden PayPal'),
        ),
    ]
