# Generated by Django 5.0.2 on 2026-03-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_pickup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_date',
        ),
    ]
