# Generated by Django 5.0.2 on 2026-03-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de recogida'),
        ),
    ]
