# Generated by Django 5.0.2 on 2026-03-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AddField(
            model_name='user',
            name='calle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='user',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='user',
            name='entre_calles',
            field=models.CharField(blank=True, max_length=200, verbose_name='Entre calles'),
        ),
        migrations.AddField(
            model_name='user',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de casa'),
        ),
        migrations.AddField(
            model_name='user',
            name='referencias',
            field=models.TextField(blank=True, verbose_name='Referencias'),
        ),
    ]
