# Generated by Django 5.0.2 on 2026-03-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
    ]
