# Generated by Django 5.0.2 on 2026-03-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_fix_cartitem_dates'),
    ]

    operations = [
    ]
