# Generated by Django 5.0.2 on 2026-03-03 22:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_fix_cartitem_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 3, 3, 22, 50, 35, 93300, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
